resources:
- manager.yaml
images:
- name: controller
  newName: ghcr.io/grafana/k6-operator
  newTag: latest@sha256:4e08d89dee3419f68ed6c4716ab8843d6602d64675e298d05e62acbb40bd9645
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
