apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    containerImage: ghcr.io/grafana/k6-operator
    repository: https://github.com/grafana/k6-operator
    support: k6
  name: k6-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: K6
      kind: K6
      name: k6s.k6.io
      version: v1alpha1
    - description: PrivateLoadZone is the Schema for the privateloadzones API
      displayName: Private Load Zone
      kind: PrivateLoadZone
      name: privateloadzones.k6.io
      version: v1alpha1
    - description: TestRun is the Schema for the testruns API
      displayName: Test Run
      kind: TestRun
      name: testruns.k6.io
      version: v1alpha1
  description: k6-operator
  displayName: k6-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - testing
  - performance
  - reliability
  - k6
  links:
  - name: k6 Operator
    url: https://github.com/grafana/k6-operator
  maintainers:
  - email: olha@k6.io
    name: Olha Yevtushenko
  - email: daniel@k6.io
    name: Daniel Gonz√°lez Lopes
  maturity: alpha
  provider:
    name: k6.io
    url: https://k6.io/
  version: 0.0.0
