---
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - grafana=https://grafana.github.io/helm-charts
helm-extra-args: --timeout 600s
check-version-increment: false
validate-maintainers: false
validate-yaml: true
validate-schema-chart: true